### ISSUE TITLE
Pflichtenheft - Verbesserungen

### ISSUE THREAD

**Issue by bschroedhtl** [2324-syp-3ahif/Hotvite#1]
**UCD**
- [x] Einige Features aus der Zielsetzung finden sich nicht im UCD wieder, z.b. das Anmelden eines Teilnehmers bei einer Veranstaltung ("Knopfdruck", setzt übrigens auch einen UC "Ansehen Events in der Nähe" voraus, der fehlt auch), Benachrichtigung bei Änderungen, Teilnehmerliste einsehen, Teilnehmerzahl begrenzen
- [x] Kann man Events auch wieder absagen?
- [x] Kann man sich von einem Event auch wieder abmelden?
- [x] Umgekehrt gibt es Use Cases, von denen in der Zielsetzung noch gar keine Rede war, z.b. "Chat" (sehe ich nur in der MindMap, dachte das wär dann rausgefallen - ist aber voll ok! Drinlassen!). Oder der Zwang, dass ein Admin einen public event freigeben muss (schiesst vlt etwas über die Hauptmotivation des Projekts, nämlich Events in der Nähe zu finden, hinaus, aber OK, wenn es Ihnen wichtig ist, machen Sie es)
- [x] Es fehlen außerdem: Profilverwaltung eines Users

**3.2 Events**
- [x] Entspricht welchem Use Case im UCD? => "Anzeige Events in der Nähe"! Fehlt im UCD
- [x] Was sind location_1, location_2, location_3 im GUI Design?
- [x] In 3.2.2 taucht plötzlich der Begriff "folgen" auf - ist das ein Feature? Wo ist das im UCD? Personen können hier auch direkt angeben ob sie kommen oder nicht? Ich kenn mich nicht aus! Entscheiden Sie sich: Restricted Events sind also private Events, sehen die alle Eingeloggten, oder muss ich explizit dazu von einem anderen eingeloggten eingeladen werden (widerspricht der Hauptmotivation des Projekts), oder muss ich einem User folgen damit ich den event sehe, oder ...? Wie ist das mit einer maximalen Teilnehmerzahl?
- [x] 3.2.3 public events: Wer ist denn ein verifizierter Account, ist mir neu? Tickets sind mir auch neu, stand bisher nirgends, oder? Maximale Teilnehmerzahl gilt hier auch?

**3.3 Event erstellen**
- [x] Was ist property4, 5? Beschreibung finde ich schon immer wichtig. Ort nur über Map? Wie ist der Ort gespeichert, nur geo location oder gibts auch eine Adresse? Mindestalter ist neu. Maximale Teilnehmerzahl? Ticket ja/nein, Ticketpreis? Public oder Restricted?

**3.4 Verwaltung**
- [x] Verwaltung von was? Schlechter Titel, seien Sie konkreter.
- [x] Warum ist das GUI über der Map gezeichnet, sehe ich jetzt eine Liste aller Events (welcher? Bin ich Admin oder normaler User? Oder Event-Ersteller?) oder nur die Events die in dem aktuellen Ausschnitt der Map drinliegen? (=> wäre meine Vermutung warum die Map bei diesem use case eine Rolle spielen könnte ...)
- [x] Was genau kann ich jetzt eigentlich machen: Event absagen und ändern, oder? => In den Titel damit. 

**3.5 Verification**
- [x] Bevor ich was verifizieren kann, muss jemand einen Verification request schicken => nicht definiert! Wäre ein Kandidat für ein ACD.
- [x] Wieder sind die Rollen hier nicht ordentlich zu Ende gedacht. Und stellen Sie besser klar, dass es hier um public events geht

**3.6 Chat**
- [x] Der unten beschriebene Workflow hat nichts mit dem eigentlichen Ablauf des Chats zu tun sondern mit der Einstellung, ob ein Event einen Chat anbietet => also gehört das noch beim Use Case Event-Erstellung dazu. Nebenfrage: Kann man den Chat im nachhinein auch wieder abdrehen (über Event ändern)? 
- [x] Im UI fehlt der Kontext, zu welchem Event dieser Chat gehört
- [x] Die User die hier sichtbar sind, sind das alle Teilnehmer des Events oder nur Teilnehmer des Events, die gerade online sind?
- [x] Wie schaut eine konkrete Chat-Historie aus? Fenster ist ziemlich leer, keine Messages

Insgesamt ist das Pflichtenheft also noch sehr lückenhaft und inkonsistent.

**Comment by Leo-Oberndorfer** [comment]
Das Pflichtenheft wurde komplett überarbeitet. Alle Punkte sollten erfüllt sein, Titel im Pflichtenheft werden noch geändert
